[functions]
  directory = "functions/"
  node_bundler = "esbuild"

[dev]
  autoLaunch = false

[build]
  publish = "dist/"
  command = "rm -rf dist/ && cp -r public dist && node scripts/build.js"

# CORS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "DNT,User-Agent,Content-Type,Cache-Control,Range"

# serverless endpoints
[[redirects]]
  from = "/ap/*"
  to = "/.netlify/functions/ap-:splat"
  status = 200
