[functions]
  node_bundler = "esbuild"

[dev]
  autoLaunch = false

[build]
  publish = "dist/"
  command = "npm run build && npm run build:fn"

[context.production.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  NODE_NO_WARNINGS = "1"

# CORS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "DNT,User-Agent,Content-Type,Cache-Control,Range"

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/jrd+json"

[[redirects]]
  from = "/.well-known/webfinger"
	to = "/.well-known/webfinger/:rs"
	status = 200
	query = { resource = ":rs" }

[[redirects]]
  from = "/ap/*"
  to = "/.netlify/functions/ap-:splat"
  status = 200
